title: The WearAbles Project
author:
  name: Christopher Thornton
  email: chris.thornton@ncl.ac.uk
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: false # set to true to show excerpts on the homepage

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://haeste.github.io/WearAbles/" # the base hostname & protocol for your site, e.g. http://example.com
root: /
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - aboutus.md
 - Devices.md
 - DataManagement.md

# Build settings
theme: minima

plugins:
 - jekyll-responsive-image
 - jekyll-feed
 - jekyll-seo-tag
