title: The WearAbles Project

description: > # We are trying to develop new methods for understanding the physiology of children in the everyday context.
show_excerpts: false # set to true to show excerpts on the homepage

url: "https://haeste.github.io/WearAbles/" # the base hostname & protocol for your site, e.g. http://example.com
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %b, %Y"


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - ResearchOverview.md
 - about.markdown
 - aboutus.md
 - Devices.md
 - DataManagement.md

# Build settings
theme: minima

plugins:
 - jekyll-responsive-image
 - jekyll-feed
 - jekyll-seo-tag
